# Generated by Django 3.0.7 on 2021-02-03 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_reply_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='comment_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='reply_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
